### ISSUE TITLE
strange effect on YAML arrays

### ISSUE THREAD

**Issue by neopaf** [dima74/intellij-indent-rainbow#42]
when I just open a file with YAML arrays, it looks sad:
```yaml
            Iterator:
              ListAttributeIterator():
                ListAttributeName:
                - _ErrorAttributes
                - _ErrorMessages
                RuleChain: AddErrorCode
                TmpAttributeName:
                - VIP_A
                - VIP_B
                AddErrorCode:
```
![Снимок экрана 2022-04-08 в 20 41 16](https://user-images.githubusercontent.com/4362564/162493909-6eeb957d-4cf8-4c41-9a05-54f0fa375e9d.png)

But once I edited likes that start with dash, it gets fixed:

![Снимок экрана 2022-04-08 в 20 42 12](https://user-images.githubusercontent.com/4362564/162494006-5636553c-9ff1-469b-9dc7-bc912f657d09.png)

One that was edited and next one get better.

plugin version 1.7.0

IntelliJ IDEA 2021.2.3 (Ultimate Edition) Build #IU-212.5457.46, built on October 12, 2021
